Certificate_AdminPanel/Models/Complaints.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace Certificate_AdminPanel.Models
{
    [Table("tbl_Complaints")]
    public class Complaints
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Display(Name="Complaint No")]
        public string ComplaintNo { get; set; }
         [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name="Complaint Date")]
        public DateTime Cdate { get; set; }
                [Required]
        public string Customer { get; set; }
        [Required]
        [Display(Name="Product Description")]
        public string ProductDescription { get; set; }
        [Required]
        [Display(Name="Serial No")]
        public string SerialNo { get; set; }
        [Required]
        [Display(Name="Complaint Details")]
        public string ComplaintDetails { get; set; }
        public string Problem { get; set; }
        public string Reason { get; set; }
         [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfReturn { get; set; }
        public string Remark { get; set; }
        public Int64 Cuser { get; set; }
        public Int64 AdminId { get; set; }
        public bool Stat { get; set; }

        [Display(Name = "Rectififed By")]
        public string RectifiedBy { get; set; }

      }
}

Certificate_AdminPanel/ViewModels/ComplaintsView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Certificate_AdminPanel.ViewModels
{
    public class ComplaintsView
    {
        public int Id { get; set; }
        [Display(Name="Complaint No")]
        public string ComplaintNo { get; set; }
         [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Cdate { get; set; }

        public string Customer { get; set; }
   
        public string ProductDescription { get; set; }
        public string SerialNo { get; set; }
        public string ComplaintDetails { get; set; }
        public string Problem { get; set; }
        public string Reason { get; set; }
         [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfReturn { get; set; }
        public string Remark { get; set; }
        public Int64 Cuser { get; set; }
        public Int64 MUser { get; set; }
        public Int64 DealerId { get; set; }
        public bool Stat { get; set; }

        public string DealerName { get; set; }

        [Display(Name="Rectififed By")]
        public string RectifiedBy { get; set; }
    }
}

Certificate_AdminPanel/Controllers/ComplaintsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Certificate_AdminPanel.Models;
using Certificate_AdminPanel.ViewModels;

namespace Certificate_AdminPanel.Controllers
{
    public class ComplaintsController : Controller
    {
        //
        // GET: /Complaints/
        [Authorize]
        public ActionResult Index()
        {
            using (DatContext db = new DatContext())
            {

                if (SessionWrapper.AdminLevel == AdminLevel.Admin)
                {

                    //var res = from a in db.complaints
                    //          where a.Stat == false
                    //          select   new 
                    //          {
                    //              Id=a.Id,
                    //              Cdate=a.Cdate,
                    //              Customer=a.Customer,
                    //              DealerId=a.AdminId,
                    //              ProductDescription=a.ProductDescription,
                    //              SerialNo=a.SerialNo,
                    //              ComplaintDetails=a.ComplaintDetails,
                    //              Cuser=a.Cuser,
                    //             AdminId=a.AdminId,
                    //             Stat=a.Stat,
                    //              DateOfReturn=a.DateOfReturn,
                    //              Remark=a.Remark,
                    //              Reason=a.Reason

                    //          };
                    var res = from a in db.complaints
                              where a.Stat == false
                              select new ComplaintsView 
                              {
                                  Id = a.Id,
                                  ComplaintNo=a.ComplaintNo,
                                  Cdate = a.Cdate,
                                  Customer = a.Customer,
                                  ProductDescription = a.ProductDescription,
                                  SerialNo = a.SerialNo,
                                  ComplaintDetails = a.ComplaintDetails,
                                  Problem = a.Problem != null ? a.Problem : "N/A",
                                  Reason = a.Reason != null ? a.Reason : "N/A",
                                  DateOfReturn = a.DateOfReturn ,
                                  Remark = a.Remark != null ? a.Remark : "N/A",
                                  Cuser = a.Cuser,
                                  RectifiedBy=a.RectifiedBy,
                                  DealerId = a.AdminId,
                                  Stat = a.Stat
                              };
                    return View(res.ToList().OrderByDescending(a=>a.Cdate));
                }
                else if (SessionWrapper.AdminLevel == AdminLevel.SubAdmin)
                {
                    var res = from a in db.complaints
                              //join  b in db.UserMst on a.Cuser equals b.UserID
                              //join c in db.CompanyMst on b.CompID equals c.CompID
                              join d in db.AdminMst on a.AdminId equals d.AdminID
                              where d.AdminID == SessionWrapper.AdminID && a.Stat == false
                              select new ComplaintsView
                              {
                                  Id=a.Id,
                                  ComplaintNo = a.ComplaintNo,
                                  Cdate = a.Cdate,
                                  Customer = a.Customer,
                                  ProductDescription = a.ProductDescription,
                                  SerialNo = a.SerialNo,
                                  ComplaintDetails = a.ComplaintDetails,
                                  Problem = a.Problem!=null?a.Problem:"N/A",
                                  Reason = a.Reason != null ? a.Reason : "N/A",
                                  DateOfReturn = a.DateOfReturn,
                                  Remark = a.Remark != null ? a.Remark : "N/A",
                                  Cuser = a.Cuser,
                                  RectifiedBy = a.RectifiedBy,
                                  DealerId=a.AdminId,
                                  Stat=a.Stat

                              };
                    return View(res.ToList().OrderByDescending(a => a.Cdate));
                }
                else if (SessionWrapper.AdminLevel == AdminLevel.CompanyAdmin)
                {
                    var res = from a in db.complaints
                              join b in db.UserMst on a.Cuser equals b.UserID
                              join c in db.CompanyMst on b.CompID equals c.CompID
                              where c.CompID == SessionWrapper.CompanyID && a.Stat == false
                              select new ComplaintsView 
                              {
                                  Id = a.Id,
                                  ComplaintNo = a.ComplaintNo,
                                  Cdate = a.Cdate,
                                  Customer = a.Customer,
                                  ProductDescription = a.ProductDescription,
                                  SerialNo = a.SerialNo,
                                  ComplaintDetails = a.ComplaintDetails,
                                  Problem = a.Problem != null ? a.Problem : "N/A",
                                  Reason = a.Reason != null ? a.Reason : "N/A",
                                  DateOfReturn = a.DateOfReturn,
                                  Remark = a.Remark != null ? a.Remark : "N/A",
                                  Cuser = a.Cuser,
                                  RectifiedBy = a.RectifiedBy,
                                  DealerId = a.AdminId,
                                  Stat = a.Stat
                              };
                    return View(res.ToList().OrderByDescending(a => a.Cdate));
                }
                else if (SessionWrapper.AdminLevel == AdminLevel.CompanyUser)
                {
                    var res = from a in db.complaints
                              join b in db.UserMst on a.Cuser equals b.UserID
                              where b.UserID == SessionWrapper.UserID && a.Stat == false
                              select new ComplaintsView 
                              {
                                  Id = a.Id,
                                  ComplaintNo = a.ComplaintNo,
                                  Cdate = a.Cdate,
                                  Customer = a.Customer,
                                  ProductDescription = a.ProductDescription,
                                  SerialNo = a.SerialNo,
                                  ComplaintDetails = a.ComplaintDetails,
                                  Problem = a.Problem != null ? a.Problem : "N/A",
                                  Reason = a.Reason != null ? a.Reason : "N/A",
                                  DateOfReturn = a.DateOfReturn,
                                  Remark = a.Remark != null ? a.Remark : "N/A",
                                  Cuser = a.Cuser,
                                  RectifiedBy = a.RectifiedBy,
                                  DealerId = a.AdminId,
                                  Stat = a.Stat
                              };
                    return View(res.ToList().OrderByDescending(a => a.Cdate));
                }

                //var res = from a in db.complaints
                //          join b in db.UserMst on a.Cuser equals b.UserID
                //          //join
                //          select new ComplaintsView
                //          {
                //              Cdate = a.Cdate,
                //              Customer = a.Customer,
                //              ProductDescription = a.ProductDescription,
                //              SerialNo = a.SerialNo,
                //              ComplaintDetails = a.ComplaintDetails,
                //              Problem = a.Problem,
                //              Reason = a.Reason,
                //              DateOfReturn = a.DateOfReturn,
                //              Remark = a.Remark,
                //              Cuser = a.Cuser,
                //              MUser = a.MUser,
                //              DealerId = a.DealerId,
                //              DealerName = b.Name
                //          };
                ////return View(db.complaints.ToList());
                //return View(res.ToList());
            }
            return View("UnAuthenticated");
        }
        [Authorize]
        public ActionResult ComplaintsRecord()
        {
            using (DatContext db = new DatContext())
            {
                if (SessionWrapper.AdminLevel == AdminLevel.Admin)
                {

                    var res = from a in db.complaints
                              join b in db.AdminMst on a.AdminId equals b.AdminID
                              where a.Stat == true
                              select new ComplaintsView
                              {
                                  Cdate = a.Cdate,
                                  ComplaintNo = a.ComplaintNo,
                                  Customer = a.Customer,
                                  ProductDescription = a.ProductDescription,
                                  SerialNo = a.SerialNo,
                                  ComplaintDetails = a.ComplaintDetails,
                                  Problem = a.Problem,
                                  Reason = a.Reason,
                                  DateOfReturn = a.DateOfReturn,
                                  Remark = a.Remark,
                                  Cuser = a.Cuser,
                                  RectifiedBy = a.RectifiedBy,
                                  DealerId = a.AdminId,

Certificate_AdminPanel/Views/Complaints/ComplaintsRecord.cshtml
@model IEnumerable<Certificate_AdminPanel.ViewModels.ComplaintsView>

@{
    ViewBag.Title = "Complaints Report";
}
@*<script src="~/Scripts/Complaints.js"></script>*@

<script type="text/javascript">
    $(document).ready(function () {

        //$("#example").dataTable({
        //    "bJQueryUI": true,
        //    //"aaSorting": [[1, "desc"]],
        //    "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [0] }],
        //    "sScrollX": "100%",
        //    "oLanguage": { "oPaginate": { "sFirst": "&lt&lt", "sLast": "&gt&gt", "sNext": "&gt", "sPrevious": "&lt" }, },
        //    "sPaginationType": "full_numbers",
        //    "bAutoWidth": false,
        //    "bScrollAutoCss": true, "bScrollCollapse": true,

        //})
        $('#example').DataTable({
            responsive: true,
            scrollY: "400px",
            scrollX: true,
            scrollCollapse: true,
            paging: true,
            fixedColumns: {
                leftColumns: 1,
                rightColumns: 1
            }
            //"sDom": 'T<"clear">lfrtip',
            //"oTableTools": {
            //    "aButtons": [
            //        "xls",
            //        "print"],
            //    "sSwfPath": "../../Content/swf/copy_csv_xls_pdf.swf"
            //}

        });
    });
</script>
<!-- Content Header (Page header) -->
</section>
<div class="content-wrapper">
    <section class="content-header">
        <h1>Complaints
       
        <small>Closed Complaint  Details</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="#">Complaint</a></li>
            <li class="active">Index</li>
        </ol>
    </section>
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Closed Complaints</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>S.No
                                    </th>
                                    <th>Complaint No
                                    </th>
                                    <th>Complaint Date
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Customer)
                                    </th>
                                    <th>Product Description
                                    </th>
                                    <th>Serial No
                                    </th>
                                    <th>Complaint Details
                                    </th>
                                    <th>Problem Found
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Reason)
                                    </th>
                                    <th>Rectified By
                                    </th>
                                    <th>Closed Date
                                    </th>

                                    <th>Remarks
                                    </th>
                                    @if (Certificate_AdminPanel.SessionWrapper.AdminLevel == AdminLevel.Admin)
                                    {
                                        <th>Admin
                                        </th>
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @{int i = 1;}
                                @foreach (var item in Model)
                                {
    
                                    <tr>
                                        <td>@i</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ComplaintNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Cdate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Customer)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProductDescription)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SerialNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ComplaintDetails)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Problem)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Reason)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.RectifiedBy)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DateOfReturn)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Remark)
                                        </td>
                                        @if (Certificate_AdminPanel.SessionWrapper.AdminLevel == AdminLevel.Admin)
                                        {
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DealerName)
                                            </td>
                                        }

                                    </tr>
                                        i = i + 1;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>


        </div>
    </section>
</div>

Certificate_AdminPanel/Views/Complaints/Create.cshtml
@model Certificate_AdminPanel.Models.Complaints

@{
    ViewBag.Title = "Create";
   
}
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/AdminTemplates/plugins/select2/select2.full.min.js"></script>
<link href="~/AdminTemplates/plugins/select2/select2.min.css" rel="stylesheet" />
<script src="~/AdminTemplates/plugins/iCheck/icheck.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //GetRegistrationDate('#Cdate');
        $("#Cdate").datepicker({
            autoclose: true,
            format: 'dd/M/yyyy'
        });

    });
</script>
@*<div style="padding-left:20em">
<h2>Register</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    
        <table class="grid">
            <tr>
                <td>

        <div class="editor-label">
           @Html.LabelFor(model=>model.Cdate)
        </div>
                    
                </td>
            <td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Cdate)
            @Html.ValidationMessageFor(model => model.Cdate)
        </div></td></tr>
            <tr>
            <td>

        <div class="editor-label">
            @Html.LabelFor(model => model.Customer)
        </div></td>
            <td>
        <div class="editor-field">
            @Html.EditorFor(model => model.Customer)
            @Html.ValidationMessageFor(model => model.Customer)
        </div></td>
                </tr>
            <tr>
            <td>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProductDescription)
        </div></td>
            <td>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProductDescription)
            @Html.ValidationMessageFor(model => model.ProductDescription)
        </div></td>
                </tr>
            <tr>
            <td>

        <div class="editor-label">
            @Html.LabelFor(model => model.SerialNo)
        </div></td>
            <td>
        <div class="editor-field">
            @Html.EditorFor(model => model.SerialNo)
            @Html.ValidationMessageFor(model => model.SerialNo)
        </div></td>
            
                </tr>
            
            <tr><td>

        <div class="editor-label">
           @Html.LabelFor(model => model.ComplaintDetails)
        </div></td>
            <td>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.ComplaintDetails,new { style="width:150px;height:60px;overflow:hidden;"})
            @Html.ValidationMessageFor(model => model.ComplaintDetails)
        </div>
                </td>
                </tr>
            
     
            <tr>
      <td>

            <input type="submit" value="Create" />
        
                    
                </td>
            </tr>
        </table>

}
        </div>
<div >*@
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Complaints
       
            <small>Complaint Registratoin</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="/Company/Index">Complaints</a></li>
            <li class="active">Registration</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">

            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Complaint Registration</h3>
                </div>

                @using (Html.BeginForm("Create", "Complaints", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
   
                    @Html.ValidationSummary(true)
   
                    <div class="box-body">
                        <!-- left column -->
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Cdate, new { @class = "col-sm-3 control-label " })

                                <div class="col-sm-7">

                                    @Html.TextBoxFor(model => model.Cdate, new { @class = "form-control cuswidth", tabindex = 1 })
                                    @Html.ValidationMessageFor(model => model.Cdate)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Customer, new { @class = "col-sm-3 control-label " })

                                <div class="col-sm-7">

                                    @Html.TextBoxFor(model => model.Customer, new { @class = "form-control cuswidth", tabindex = 2 })
                                    @Html.ValidationMessageFor(model => model.Customer)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProductDescription, new { @class = "col-sm-3 control-label " })

                                <div class="col-sm-7">

                                    @Html.TextAreaFor(model => model.ProductDescription, new { @class = "form-control cuswidth", tabindex = 3 })
                                    @Html.ValidationMessageFor(model => model.ProductDescription)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.SerialNo, new { @class = "col-sm-3 control-label " })

                                <div class="col-sm-7">

                                    @Html.TextBoxFor(model => model.SerialNo, new { @class = "form-control cuswidth", tabindex = 4 })
                                    @Html.ValidationMessageFor(model => model.SerialNo)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ComplaintDetails, new { @class = "col-sm-3 control-label " })

                                <div class="col-sm-7">

                                    @Html.TextAreaFor(model => model.ComplaintDetails, new { @class = "form-control cuswidth", style = "width:100%", tabindex = 5 })

                                    @Html.ValidationMessageFor(model => model.ComplaintDetails)
                                </div>


                            </div>
                        </div>

                    </div>
                }
                <div class="box-footer">
                    @Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-info pull-left", tabindex = 6 })
                    <button type="submit" class="btn btn-info pull-right" tabindex="7">Submit</button>
                </div>


            </div>
    </section>


</div>

Certificate_AdminPanel/Views/Complaints/Delete.cshtml
@model Certificate_AdminPanel.Models.Complaints

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete:<strong></strong> </h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="OK" /> |
        <input type="button" value="Cancel" onclick="window.location='@Url.Action("Index")'" class="button" />
 
    </p>
}