Certificate_AdminPanel/ViewModels/companyview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Certificate_AdminPanel.Models;
using System.ComponentModel.DataAnnotations.Schema;
using DatePickerTemp.Infrastructure;

namespace Certificate_AdminPanel.ViewModels
{
    
    public class companyview : Gena
    {
        [Key, DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public Int64 CompID { get; set; }

        [Required]
        [RegularExpression("^([a-zA-Z0-9 .-]+)$", ErrorMessage = "Invalid  Name")]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]
        [RegularExpression("^([a-zA-Z0-9 .-]+)$", ErrorMessage = "Invalid  Name")]
        [DataType(DataType.Text)]
        public string DisplayName { get; set; }

        [Required]
        //[RegularExpression("^([a-zA-Z0-9 .-]+)$", ErrorMessage = "Invalid  Name")]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }

        [Required]
        [RegularExpression("(^(\\+?\\-? *[0-9]+)([,0-9 ]*)([0-9 ])*$)|(^ *$)", ErrorMessage = "Invalid number")]
        public string PhoneNo { get; set; }

        [Required]
        [RegularExpression("(^(\\+?\\-? *[0-9]+)([,0-9 ]*)([0-9 ])*$)|(^ *$)", ErrorMessage = "Invalid number")]
        public string MobileNo { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", ErrorMessage = "Invalid Email")]
        public string Email { get; set; }

        public Int64 UserID { get; set; }

        [Required]
        public Int32 TimeZoneID { get; set; }

        // [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        //[DataType(DataType.Date)]
        [Required]
        //[DateRange(Min = "2010/12/02", Max = "2015/12/20")]
        public DateTime MDate { get; set; }

        //[Required]
        public string Logo { get; set; }

        [Required]
        //[DataType(DataType.Date)]
        //[DateRange(Min="2010/12/02",Max="2015/12/20")]
        [DisplayFormat(DataFormatString = "{0:dd'/'MMM'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ExpDate { get; set; }

        [UIHint("DropDownList")]
        [Required(ErrorMessage = "You must select a Contact Prefix")]
        public Int64 AdminID { get; set; }

        //[Key]
        //public string UserID { get; set; }

        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string pwd { get; set; }
        //[Key]
        //public string AdminID { get; set; }

        public string AdminName { get; set; }
        [Key]
        public Int32 tab_id { get; set; }

        public string time_zone { get; set; }
        //public string 
        public string adminlogo { get; set; }
        //[ForeignKey("AdminID")]
        //public virtual AdminMaster AdminMst { get; set; }

        //[ForeignKey("UserID")]
        //public virtual UserMaster UserMst { get; set; }

        //[ForeignKey("TimeZoneID")]
        //public virtual GmtZone gmtzn { get; set; }
        //public IEnumerable<GmtZone> GMT_ZONE { get; set; }
        [NotMapped]
        public bool isLogin { get; set; }
    }




}

Certificate_AdminPanel/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Certificate_AdminPanel.Models;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Certificate_AdminPanel.ViewModels;
using System.Data.SqlClient;

namespace Certificate_AdminPanel.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {

        private DatContext db = new DatContext();
        List<string> loggedInUsers = (List<string>)HttpRuntime.Cache["LoggedInUsers"];
      
        string password_create;
        string loginname_create;
        string path_create;
        //
        // GET: /Company/
        [Audit]
        public ActionResult Index()
        {

            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetExpires(DateTime.UtcNow.AddHours(-1));
            Response.Cache.SetNoStore();
            try
            {
                if (SessionWrapper.IsAdmin)
                {

                    //var companymst = db.CompanyMst.Include(c => c.AdminMst).Include(c => c.UserMst).Include(c => c.gmtzn);
                    if (SessionWrapper.AdminLevel == AdminLevel.Admin)
                    {
                        var com = (from a in db.CompanyMst
                                  join b in db.AdminMst on a.AdminID equals b.AdminID
                                  join c in db.UserMst on a.CompID equals c.CompID
                                  join d in db.GMT_ZONE on a.TimeZoneID equals d.tab_id
                                  join e in db.LoginMst on c.UserID equals e.UserID
                                  where a.E_Stat==true
                                  select new companyview
                                  {
                                      CompID=a.CompID,
                                      Name = a.Name,
                                      DisplayName = a.DisplayName,
                                      Address = a.Address,
                                      PhoneNo = a.PhoneNo,
                                      MobileNo = a.MobileNo,
                                      Email = a.Email,
                                      Logo=a.Logo,
                                      LoginName=e.LoginName,
                                      pwd=e.pwd,
                                      //UserID=a.UserID,
                                      E_Stat=a.E_Stat,
                                      //TimeZoneID = a.TimeZoneID,
                                      ExpDate = a.ExpDate,
                                      CDate = a.CDate,
                                      MDate=a.MDate,
                                      AdminID=a.AdminID,
                                     // UserName =c.Name,
                                      AdminName=b.Name,
                                      time_zone=d.time_zone,
                                      isLogin = loggedInUsers.Contains(e.LoginName) ? true : false
                                  }).GroupBy(a=>a.CompID).Select(g=>g.FirstOrDefault());

                        //var com = from a in db.CompanyMst
                        //          join b in db.GMT_ZONE on a.TimeZoneID equals b.tab_id
                        //          select new companyview
                        //              {
                        //                  Name = a.Name,
                        //                  DisplayName = a.DisplayName,
                        //                  Address = a.Address,
                        //                  PhoneNo = a.PhoneNo,
                        //                  MobileNo = a.MobileNo,
                        //                  Email = a.Email,
                        //                  // UserID=a.UserID,
                        //                  TimeZoneID = a.TimeZoneID,
                        //                  ExpDate = a.ExpDate,
                        //                  CDate = a.CDate,
                        //                   //AdminID=a.AdminID,
                        //                  time_zone = b.time_zone,

                        //              };
                         //companymst = from co in companymst orderby co.CompID select co;
                         return View(com);
                    }
                    else if (SessionWrapper.AdminLevel == AdminLevel.SubAdmin)
                    {
                        //var companymst = db.CompanyMst.Include(c => c.AdminMst).Include(c => c.UserMst).Include(c => c.gmtzn);
                      var com = (from a in db.CompanyMst
                                  join b in db.AdminMst on a.AdminID equals b.AdminID
                                  join c in db.UserMst on a.CompID equals c.CompID
                                  join d in db.GMT_ZONE on a.TimeZoneID equals d.tab_id
                                  join e in db.LoginMst on c.UserID equals e.UserID 
                                  where a.AdminID==SessionWrapper.AdminID && a.E_Stat==true
                                  select new companyview
                                  {
                                      CompID=a.CompID,
                                      Name = a.Name,
                                      DisplayName = a.DisplayName,
                                      LoginName=e.LoginName,
                                      pwd=e.pwd,
                                      Address = a.Address,
                                      PhoneNo = a.PhoneNo,
                                      MobileNo = a.MobileNo,
                                      Email = a.Email,
                                      Logo=a.Logo,
                                      ExpDate = a.ExpDate,
                                      CDate = a.CDate,
                                      MDate=a.MDate,
                                      //UserID=a.UserID,
                                      AdminID=a.AdminID,
                                      E_Stat=a.E_Stat,
                                      //UserName =c.Name,
                                      AdminName=b.Name,
                                      time_zone=d.time_zone,
                                      isLogin = loggedInUsers.Contains(e.LoginName) ? true : false
                                  }).GroupBy(a=>a.CompID).Select(g=>g.FirstOrDefault());
                        
                        //return View(companymst);
                        //companymst = from co in companymst where co.AdminID == SessionWrapper.AdminID orderby co.CompID select co;
                        return View(com);
                    }
                }

            }
            catch (Exception)
            {
                throw;
            }
            return View("UnAuthenticated");
        }

        //
        // GET: /Company/Details/5
        [Audit]
        public ActionResult Details(long? id)
        {
            try
            {
                if (SessionWrapper.AdminLevel == AdminLevel.Admin||SessionWrapper.AdminLevel==AdminLevel.SubAdmin)
                {
                    CompanyMaster companymaster = db.CompanyMst.Find(id);
                    AdminMaster admn = db.AdminMst.Find(companymaster.AdminID);
                    //var usr = db.UserMst.Where(a => a.Name == (db.CompanyMst.Find(id)).Name);
                    UserMaster us = db.UserMst.FirstOrDefault(a => a.CompID == companymaster.CompID);
                    LoginMaster lgn = db.LoginMst.FirstOrDefault(a=>a.UserID==us.UserID);
                    GmtZone GMT = db.GMT_ZONE.Find(companymaster.TimeZoneID);
                   
                    return PartialView(new companyview 
                    {
                        CompID = companymaster.CompID,
                        Name = companymaster.Name,
                        DisplayName = companymaster.DisplayName,
                        LoginName = lgn.LoginName,
                        pwd = lgn.pwd,
                        Address = companymaster.Address,
                        PhoneNo = companymaster.PhoneNo,
                        MobileNo = companymaster.MobileNo,
                        Email = companymaster.Email,

                        ExpDate = companymaster.ExpDate,
                        CDate = companymaster.CDate,
                        MDate = companymaster.MDate,
                        //UserID=a.UserID,
                        AdminID = admn.AdminID,
                       // E_Stat = companymaster.E_Stat,
                        //UserName =c.Name,
                        AdminName = admn.Name,
                        time_zone = GMT.time_zone,
                    
                    });
                }
                else 
                {
                    return View("UnAuthenticated");
                }
            }
            catch (Exception)
            {
                throw;
            }
            
        }

        ////
        //// GET: /Company/Create
        //public ActionResult Details()
        //{
        //    var abc = from a in db.CompanyMst join b in db.GMT_ZONE on a.TimeZoneID equals b.tab_id select new companyview 
        //    {Name=a.Name,
        //    DisplayName=a.DisplayName,
        //    Address=a.Address,
        //    PhoneNo=a.PhoneNo,
        //    MobileNo=a.MobileNo,
        //    Email=a.Email,
        //    UserID=a.UserID,
        //    TimeZoneID=a.TimeZoneID,
        //    ExpDate=a.ExpDate,
        //    CDate=a.CDate,
        //    AdminID=a.AdminID,
        //    time_zone=b.time_zone,
        //    };
        //    return View(abc);
           
        //}
       
        public ActionResult Create()
        {
            if (SessionWrapper.AdminLevel == AdminLevel.Admin || SessionWrapper.AdminLevel == AdminLevel.SubAdmin)
            {
                filldropdowns();

Certificate_AdminPanel/Views/Company/Delete.cshtml
@model Certificate_AdminPanel.Models.CompanyMaster

@{
    ViewBag.Title = "Delete";

    Layout = null;
}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete</h4>
    </div>

    <div class="modal-body">
        <p>Are you sure want to delete&hellip;?</p>
    </div>


    @using (Html.BeginForm())
    {
        <div class="modal-footer">

            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-outline">Ok</button>

        </div>
    }

</div>

Certificate_AdminPanel/Views/Company/Details.cshtml
@model Certificate_AdminPanel.ViewModels.companyview

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminTemplate.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Manager
       
        <small>Details</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="/Company/Index">Manager</a></li>
            <li class="active">Details</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Details</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-striped">

                            <colgroup>
                                <col class="col-grp-left">
                                <col class="col-grp-right">
                            </colgroup>
                            <tr>
                                <td>
                                    <div class="display-label">
                                        Name
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.Name)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="display-label">
                                        Display Name
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.DisplayName)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.LoginName)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.LoginName)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="display-label">
                                        Password
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.pwd)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.Address)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.Address)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.PhoneNo)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.PhoneNo)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.MobileNo)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.MobileNo)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.Email)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.Email)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.time_zone)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.time_zone)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.CDate)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.CDate)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <div class="display-label">
                                        @Html.DisplayNameFor(model => model.MDate)
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.MDate)
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <div class="display-label">
                                        Admin
                                    </div>
                                </td>
                                <td>
                                    <div class="display-field">
                                        @Html.DisplayFor(model => model.AdminName)
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="box-footer">
                                             @Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-info pull-left" })

                     
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Certificate_AdminPanel/Views/Company/Edit.cshtml
@model Certificate_AdminPanel.Models.CompanyMaster

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminTemplate.cshtml";
}
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/AdminTemplates/plugins/select2/select2.full.min.js"></script>
<link href="~/AdminTemplates/plugins/select2/select2.min.css" rel="stylesheet" />
<script src="~/AdminTemplates/plugins/iCheck/icheck.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        var CompID = $('#CompID').val();
        $.getJSON("../../../../Company/ImageUpload", { ID: CompID }, function (ImageSrc) {
            $("#imgphoto").attr("src", ImageSrc);

        });
        //Date assign to textbox..       
        //GetExpDate('#ExpDate');
        //document.getElementById('ExpDate').readOnly = 'readonly';

        $(".select2").select2();
        $("#ExpDate").datepicker({
            autoclose: true,
            format: 'dd/M/yyyy'
        });
    });
</script>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Dealer
       
            <small>Dealer Edit form</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="/Company/Index">Manager</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">

            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit</h3>
                </div>

                @using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.HiddenFor(model => model.CompID)
                    @Html.HiddenFor(model => model.E_Stat)
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="box-body">

                        <!-- left column -->
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Name)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.DisplayName, new { @class = "col-sm-2 control-label" })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.DisplayName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.DisplayName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Address, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Address)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MobileNo, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MobileNo)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.TimeZoneID, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.DropDownListFor(model => model.TimeZoneID, (IEnumerable<SelectListItem>)ViewBag.bind_drop_zone, "-select-", new { @class = "form-control select2" })

                                    @Html.ValidationMessageFor(model => model.TimeZoneID)
                                </div>
                            </div>

                        </div>
                        <!-- right column -->
                        <div class="col-sm-6">


                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.PhoneNo, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.PhoneNo, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PhoneNo)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Logo, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">
                                    <input type="text" readonly="" class="form-control" placeholder="Browse..." id="file_name">

                                    <input data-val="true" data-val-required="field required" type="file" name="file" id="Logo" style="width: 150px;" class="form-control" onchange="document.getElementById('file_name').value=this.value" />

                                    @Html.ValidationMessage("file")
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ExpDate, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.ExpDate,"{0:dd/MMM/yyyy}", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ExpDate)
                                </div>
                            </div>
                            @if (Certificate_AdminPanel.SessionWrapper.AdminLevel == AdminLevel.Admin)
                            {
                                <div class="form-group">
                                    @Html.LabelFor(model => model.AdminID, new { @class = "col-sm-2 control-label " })

                                    <div class="col-sm-10">

                                        @Html.DropDownListFor(model => model.AdminID, (IEnumerable<SelectListItem>)ViewBag.AdminIDs, "-select-", new { @class = "form-control select2" })

                                        @Html.ValidationMessageFor(model => model.AdminID)
                                    </div>
                                </div>
                            }
                        </div>

                    </div>
                    <div class="box-footer">
                                             @Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-info pull-left" })

                        <button type="submit" class="btn btn-info pull-right">Save</button>
                    </div>
                }

            </div>
        </div>
    </section>

</div>