Certificate_AdminPanel/Controllers/AdministerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Certificate_AdminPanel.Models;
using System.Web.Helpers;
using System.Web.UI.WebControls;
using System.IO;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Net;

using System.Security.Cryptography;
using System.Text;
using System.Web.Security;

using System.Configuration;
using System.Data.SqlClient;
using Certificate_AdminPanel.ViewModels;



namespace Certificate_AdminPanel.Controllers
{


    public class AdministerController : Controller
    {

        private DatContext db = new DatContext();
        List<string> loggedInUsers = (List<string>)HttpRuntime.Cache["LoggedInUsers"];
        string logo_path;
        //
        // GET: /Admin/
        [Authorize, Audit]
       
        public ActionResult Index()
        {
            //using(DatContext db=new DatContext())
            //{
            //Regex objAlphaPattern = new Regex(@"^[a-zA-Z0-9_@.-]*$");
            //bool sts = objAlphaPattern.IsMatch(username);
            //Response.Cache.SetCacheability(HttpCacheability.NoCache);
            //Response.Cache.SetExpires(DateTime.UtcNow.AddHours(-1));
            //Response.Cache.SetNoStore();
            if (SessionWrapper.AdminLevel == AdminLevel.Admin)
            {
                //System.Threading.Thread.Sleep(5000);
                //var adminmst = db.AdminLogin.Include(a => a.AdminMaster);
                var adminmst = (from a in db.AdminLogin
                                join b in db.AdminMst on a.AdminID equals b.AdminID
                                join c in db.GMT_ZONE on b.TimeZoneID equals c.tab_id
                                where a.E_Stat == true
                                select new admin
                                    {
                                        LoginID = a.LoginID,
                                        AdminID = a.AdminID,
                                        Name = b.Name,
                                        LoginName = a.LoginName,
                                        Password = a.Password,
                                        pwd = a.pwd,
                                        DisplayName = b.DisplayName,
                                        Address = b.Address,
                                        PhoneNo = b.PhoneNo.Trim(),
                                        MobileNo = b.MobileNo.Trim(),
                                        Email = b.Email,
                                        TimeZoneID = b.TimeZoneID,
                                        Logo = b.Logo,
                                        MDate = b.MDate,
                                        ExpDate = b.ExpDate,
                                        CDate = a.CDate,
                                        Type = a.Type,
                                        E_Stat = a.E_Stat,
                                        RoleID = a.RoleID,
                                        Gmt_minute = c.Gmt_minute,
                                        time_zone = c.time_zone,
                                        TemplateName = db.Template.FirstOrDefault(xx => xx.ID == b.TemplateID) != null ? db.Template.FirstOrDefault(xx=>xx.ID==b.TemplateID).TemplateName : "N/A",
                                        isLogin = loggedInUsers.Any(xx=>xx.Contains(a.LoginName))?true:false

                                    }).ToList().OrderByDescending(xx => xx.CDate).ToList(); ;

                //adminmst = from dat in adminmst orderby dat.AdminID select dat;
                return View(adminmst);
            }

            //else if (SessionWrapper.AdminLevel == AdminLevel.SubAdmin)
            //{
            //    var admn = from a in db.AdminLogin
            //               join b in db.AdminMst on a.AdminID equals b.AdminID
            //               join c in db.GMT_ZONE on b.TimeZoneID equals c.tab_id where a.E_Stat==true
            //               select new admin
            //               {
            //                   Name = b.Name,
            //                   LoginName = a.LoginName,
            //                   DisplayName = b.DisplayName,
            //                   Address = b.Address,
            //                   PhoneNo = b.PhoneNo,
            //                   MobileNo = b.MobileNo,
            //                   Email = b.Email,
            //                   TimeZoneID = b.TimeZoneID,
            //                   Logo=b.Logo,
            //                   MDate = b.MDate,
            //                   ExpDate = b.ExpDate,
            //                   CDate = a.CDate,
            //                   Type = a.Type,
            //                   time_zone = c.time_zone,


            //               };
            //    return View(admn);

            //var adminmst = db.AdminLogin.Include(a => a.AdminMaster);
            //adminmst = from dat in adminmst where dat.AdminID == SessionWrapper.AdminID orderby dat.AdminID select dat;
            //return View(adminmst);
            //}

            return View("LogOn");

            //}
        }


        //GET: /Admin/Details/5
        [Authorize, Audit]
        public ActionResult Details(long id)
        {
            if (SessionWrapper.AdminLevel == AdminLevel.Admin)
            {
                AdminLogin adminlogin = db.AdminLogin.Find(id);
                AdminMaster admn = db.AdminMst.Find(adminlogin.AdminMaster.AdminID);
                GmtZone GMT = db.GMT_ZONE.Find(adminlogin.AdminMaster.TimeZoneID);
                return PartialView(new admin
                {
                    //LoginID = adminlogin.LoginID,
                    //AdminID = adminlogin.AdminID,
                    Name = admn.Name,
                    LoginName = adminlogin.LoginName,
                    Password = adminlogin.Password,
                    pwd = adminlogin.pwd,
                    DisplayName = admn.DisplayName,
                    Address = admn.Address,
                    PhoneNo = admn.PhoneNo.Trim(),
                    MobileNo = admn.MobileNo.Trim(),
                    Email = admn.Email,
                    TimeZoneID = GMT.tab_id,
                    time_zone = GMT.time_zone,
                    Logo = admn.Logo,
                    MDate = admn.MDate,
                    ExpDate = admn.ExpDate,
                    CDate = admn.CDate,
                    Type = admn.Type,
                    E_Stat = admn.E_Stat,


                });
            } return View("UnAuthenticated");
        }

        //
        // GET: /Admin/Create
        [Authorize]
        public ActionResult Create()
        {
            if (SessionWrapper.AdminLevel == AdminLevel.Admin)
            {
                getdropdowns();
                return PartialView();
            }
            return View("UnAuthenticated");
        }

        //
        // POST: /Admin/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(AdminLogin adminlogin, HttpPostedFileBase file)
        {
            //using (DatContext db = new DatContext())
            //{
            var t = this.ModelState.Keys.SelectMany(key => (this.ModelState[key].Errors));
            if (SessionWrapper.AdminLevel == AdminLevel.Admin)
            {
                if (db.AdminLogin.Count(a => a.LoginName == adminlogin.LoginName) > 0)
                {
                    ModelState.AddModelError("LoginName", "login name already exists !!");

                }
                //else if (db.AdminMst.Count(a => a.Name == adminlogin.AdminMaster.Name) > 0)
                //{
                //    ModelState.AddModelError("Name", "admin name already exists !!");
                //}
                //else if (adminlogin.AdminMaster.ExpDate < DateTime.Now)
                //{
                //    ModelState.AddModelError("AdminMaster.ExpDate", "date should be graiter than current date !!");
                //}
                else if (file == null)
                { ModelState.AddModelError("AdminMaster_logo", "please select logo "); }
                DateTime cdate = DateTime.UtcNow;
                adminlogin.CDate = cdate;
                adminlogin.AdminMaster.CDate = cdate;
                adminlogin.AdminMaster.MDate = cdate;
                adminlogin.AdminMaster.UserID = 1;
                // adminlogin.AdminMaster.UserID = db.AdminLogin.SingleOrDefault(a => a.LoginName == HttpContext.User.Identity.Name).AdminID;
                adminlogin.AdminMaster.UpperAdminID = adminlogin.AdminMaster.UserID;
                adminlogin.AdminMaster.Type = 1;
                adminlogin.Type = 1;
                adminlogin.RoleID = 1;
                adminlogin.AdminMaster.E_Stat = true;
                adminlogin.E_Stat = true;
                if (adminlogin.Password != null)
                {
                    adminlogin.pwd = adminlogin.Password;
                    adminlogin.Password = GetMD5Hash(adminlogin.Password);

                }
                adminlogin.AdminID = adminlogin.AdminMaster.AdminID;
                adminlogin.AdminMaster.TemplateID = adminlogin.AdminMaster.TemplateID;
                if (ModelState.IsValid)
                {
                    if ((file != null) && (file.ContentLength > 0))
                    {
                        if (file.ContentType.Equals("image/jpeg"))
                        {
                            var guid = Guid.NewGuid();
                            try
                            {
                                file.SaveAs(Server.MapPath("/Content/images/logo/" + string.Format(@"{0}", guid) + file.FileName));
                            }
                            catch (DirectoryNotFoundException)
                            {

Certificate_AdminPanel/Views/Administer/ChangePassword.cshtml
@model Certificate_AdminPanel.Models.AdminLogin

@{
    ViewBag.Title = "Change Password";
    
}


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Administer
       
            <small>Change Password form</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="/Administer/Index">Administer</a></li>
            <li class="active">Change Password</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">

            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Password</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("ChangePassword", "Administer", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                { 
                    @Html.HiddenFor(model => model.LoginID)
                    @Html.HiddenFor(model => model.Type)
                    @Html.HiddenFor(model => model.RoleID)
                    @Html.HiddenFor(model => model.E_Stat)
                    @Html.HiddenFor(model => model.AdminID)
                    @Html.HiddenFor(model => model.CDate)
        
                    <div class="box-body">

                        <!-- left column -->
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.LoginName, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.LoginName, new { @class = "form-control", style = "width:265px" })
                                    @Html.ValidationMessageFor(model => model.LoginName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.Password, new { @class = "form-control", style = "width:265px" })
                                    @Html.ValidationMessageFor(model => model.Password)
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="ConfirmPassword" class="col-sm-2 control-label ">Confirm New Password</label>

                                <div class="col-sm-10">

                                    <input class="text-box single-line password form-control" data-val="true" data-val-equalto="Password must match" data-val-equalto-other="*.Password" id="ConfirmPassword" name="ConfirmPassword" type="password" value="" style="width: 265px" />
                                    <span class="field-validation-valid" data-valmsg-for="ConfirmPassword" data-valmsg-replace="true"></span>

                                </div>
                            </div>
                        </div>

                    </div>
   
                    <div class="box-footer">
                        @Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-info pull-left" })
                        <button type="submit" class="btn btn-info pull-right">Save</button>
                    </div>
                }
            </div>
        </div>
    </section>

</div>

Certificate_AdminPanel/Views/Administer/ChangePasswordSuccess.cshtml
@{
    ViewBag.Title = "Change Password";
}

<h2>Change Password</h2>
<p>
    Your password has been changed successfully.
</p>

Certificate_AdminPanel/Views/Administer/Create.cshtml
@model Certificate_AdminPanel.Models.AdminLogin

@{
    ViewBag.Title = "Create";
    // Layout = "~/Views/Shared/_LayoutFancybox.cshtml";
    Layout = "~/Views/Shared/_AdminTemplate.cshtml";
}
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/AdminTemplates/plugins/select2/select2.full.min.js"></script>
<link href="~/AdminTemplates/plugins/select2/select2.min.css" rel="stylesheet" />
<script src="~/AdminTemplates/plugins/iCheck/icheck.min.js"></script>
@*<style>
    .select2-container--default .select2-selection--single .select2-selection__rendered {
        line-height: 23px;
    }
  
</style>*@
<script type="text/javascript">
    $(document).ready(function () {
        //// $('#AdminMaster_ExpDate').datepicker({ dateFormat: "dd-M-yy", changeYear: true, changeMonth: true, showOn: 'button', buttonImageOnly: true, buttonImage: '../../Content/Images/DatetimePicker/icon_cal.png' });
        //$('#CDate').datepicker({ dateFormat: "dd/M/yy", changeYear: true, changeMonth: true, showOn: 'button', buttonImageOnly: true, buttonImage: '../../Content/Images/DatetimePicker/icon_cal.png' });
        $(".select2").select2();
        $("#AdminMaster_ExpDate").datepicker({
            autoclose: true,
            format: 'dd/M/yyyy'
        });

    });
    //document.getElementById('AdminMaster_ExpDate').readOnly = 'readonly';

    // GetExpDate('#AdminMaster_ExpDate');
    //Initialize Select2 Elements

</script>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Administer
       
            <small>Admin Creation form</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="/Administer/Index">Administer</a></li>
            <li class="active">Admin Creation</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">

            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Admin Creation</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("Create", "Administer", FormMethod.Post, new { enctype = "multipart/form-data", id = "myForm1", @class = "form-horizontal" }))
                {
                    <div class="box-body">
                        <!--/.col (left) -->
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.Name, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">
                                    @Html.TextBoxFor(model => model.AdminMaster.Name, new { @class = "form-control",tabindex=1 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.Name)

                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.LoginName, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.LoginName, new { @class = "form-control" ,tabindex=3})
                                    @Html.ValidationMessageFor(model => model.LoginName)
                                </div>
                            </div>
                            <div class="form-group">

                                <label for="ConfirmPassword" class="col-sm-2 control-label ">Confirm Password</label>
                                <div class="col-sm-10">

                                    <input class="text-box single-line password form-control" data-val="true" tabindex="5" data-val-equalto="Password must match" data-val-equalto-other="*.Password" id="ConfirmPassword" name="ConfirmPassword" type="password" value="" />
                                    <span class="field-validation-valid" data-valmsg-for="ConfirmPassword" data-valmsg-replace="true"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.MobileNo, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.AdminMaster.MobileNo, new { @class = "form-control",tabindex=7 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.MobileNo)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.Email, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.AdminMaster.Email, new { @class = "form-control",tabindex=9 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.Logo, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">
                                    <input type="text" readonly="" class="form-control" name="file" placeholder="Browse..." id="file_name",tabindex="11">

                                    <input data-val="true" data-val-required="field required" type="file" name="file" id="file" onchange="document.getElementById('file_name').value = this.value" style="width: 150px;" class="form-control" />
                                    @Html.ValidationMessage("file")
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.TemplateID, new { @class = "col-sm-2 control-label Template " })

                                <div class="col-sm-10">

                                    @Html.DropDownListFor(model => model.AdminMaster.TemplateID, (IEnumerable<SelectListItem>)ViewBag.templatelist, "-select-", new { style = "width:100%;", @class = "form-control select2" ,tabindex=13})
                                    @Html.ValidationMessageFor(model => model.AdminMaster.TemplateID)
                                </div>
                            </div>
                        </div>
                        <!--/.col (left) -->
                        <!--/.col (right) -->
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.DisplayName, new { @class = "col-sm-2 control-label" })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.AdminMaster.DisplayName, new { @class = "form-control" ,tabindex=2 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.DisplayName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control",tabindex=4 })
                                    @Html.ValidationMessageFor(model => model.Password)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.Address, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextAreaFor(model => model.AdminMaster.Address, new { @class = "form-control", rows = 3,tabindex=6 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.Address)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.PhoneNo, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.AdminMaster.PhoneNo, new { @class = "form-control",tabindex=8 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.PhoneNo)
                                </div>
                            </div>
                           
                            <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.ExpDate, new { @class = "col-sm-2 control-label " })



                                <div class="col-sm-10">

                                    @Html.TextBoxFor(model => model.AdminMaster.ExpDate, new { @class = "form-control pull-right",tabindex=10 })
                                    @Html.ValidationMessageFor(model => model.AdminMaster.ExpDate)
                                </div>


                            </div>
                             <div class="form-group">
                                @Html.LabelFor(model => model.AdminMaster.TimeZoneID, new { @class = "col-sm-2 control-label " })

                                <div class="col-sm-10">

                                    @Html.DropDownListFor(model => model.AdminMaster.TimeZoneID, (IEnumerable<SelectListItem>)ViewBag.timezone, "-select-", new { style = "width:100%;", @class = "form-control select2",tabindex=12 })
                                    @*@Html.EditorFor(model=>model.AdminMaster.TimeZoneID)*@
                                    @Html.ValidationMessageFor(model => model.AdminMaster.TimeZoneID)
                                </div>
                            </div>

                            <!--/.col (right) -->
                        </div>
                        <!-- /.box-body -->

                    </div>
                    <div class="box-footer">
                         @Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-info pull-left",tabindex=14    })
                        <button type="submit" class="btn btn-info pull-right" tabindex="15">Submit</button>
                    </div>
                    <!-- /.box-footer -->
                }
            </div>


        </div>


    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Certificate_AdminPanel/Views/Administer/Delete.cshtml
@model Certificate_AdminPanel.Models.AdminLogin

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete</h4>
    </div>

    <div class="modal-body">
        <p>Are you sure want to delete&hellip;?</p>
    </div>


    @using (Html.BeginForm())
    {
        <div class="modal-footer">

            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-outline">Ok</button>

        </div>
    }

</div>

Certificate_AdminPanel/Views/Administer/Details.cshtml
@model Certificate_AdminPanel.ViewModels.admin

@{
    ViewBag.Title = "Details";
    //Layout = "~/Views/Shared/_LayoutFancybox.cshtml";
    Layout = "~/Views/Shared/_AdminTemplate.cshtml";
}


@*<style>
    table {
        width: 100%;
        padding: 5px;
    }

    div h2 {
        display: block;
        text-align: center;
    }

    th, td {
        text-align: left;
        padding: 10px;
        border: 1px solid black;
    }
</style>*@
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Administer
       
        <small>Details</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="#">Administer</a></li>
            <li class="active">Details</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Details</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-striped">


                            <tr>
                                <th>Name</th>
                                <td>@Html.DisplayFor(model => model.Name)</td>
                                <th>Display Name</th>
                                <td>@Html.DisplayFor(model => model.DisplayName)</td>
                            </tr>

                            <tr>
                                <th>LoginName</th>
                                <td>@Html.DisplayFor(model => model.LoginName)</td>
                                <th>PhoneNo</th>
                                <td>@Html.DisplayFor(model => model.PhoneNo)</td>
                            </tr>
                            <tr>
                                <th>Address</th>
                                <td colspan="3">@Html.DisplayFor(model => model.Address)</td>
                            </tr>
                            <tr>
                                <th>MobileNo</th>
                                <td>@Html.DisplayFor(model => model.MobileNo)</td>
                                <th>Email</th>
                                <td>@Html.DisplayFor(model => model.Email)</td>
                            </tr>

                            <tr>
                                <th>Time Zone</th>
                                <td>@Html.DisplayFor(model => model.time_zone)</td>
                                <th>Created Date</th>
                                <td>@Html.DisplayFor(model => model.CDate)</td>
                            </tr>

                            <tr>
                                <th>Modified Date</th>
                                <td>@Html.DisplayFor(model => model.MDate)</td>
                                <th>@Html.DisplayNameFor(model => model.Type)</th>
                                <td>@Html.DisplayFor(model => model.Type)</td>
                            </tr>


                        </table>
                    </div>
                    <div class="box-footer">
                        @Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-info pull-left" })

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>